---
inputs:
  dependencies:
    description: List of package(s) to pre-install
    required: false
  groups:
    description: List of group(s) to install
    required: false
  packages:
    description: List of package(s) to install
    required: true

runs:
  using: composite
  steps:
    - name: Cache `DNF` / `YUM`
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/dnf
          /var/lib/dnf
          /var/cache/yum
        key: ${{ matrix.image }}-yum-dnf

    - name: Install dependency package(s)
      run: |
        if [ -n "${{ inputs.dependencies }}" ]; then
          yum --assumeyes install ${{ inputs.dependencies }}
        fi
      shell: bash --noprofile --norc -euxo pipefail {0}

    - name: Install group(s)
      run: |
        if [ -n '${{ inputs.groups }}' ]; then
          yum --assumeyes groups install ${{ inputs.groups }}
        fi
      shell: bash --noprofile --norc -euxo pipefail {0}

    - name: Install package(s)
      run: yum --assumeyes --skip-broken install ${{ inputs.packages }}
      shell: bash --noprofile --norc -euxo pipefail {0}
